library(Seurat)
library(glue)
library(qs)
library(nicheDE)
library(clusterProfiler)
library(org.Hs.eg.db)
library(parallel)
library(ggplot2)
library(stringr)
library(ggsci)
library(reshape2)
library(scales)
library(hues)
library(RColorBrewer)
library(latex2exp)
library(MASS)
library(irr)
library(patchwork)
library(ggdark)
library(CellChat)
library(spdep)
library(SpatialExperiment)
library(ComplexHeatmap)
library(Polychrome)
library(scico)
library(SEraster)
library(dplyr)
library(tidyr)

options(future.globals.maxSize = 8.0 * 1e9)

sample_id <- commandArgs(trailingOnly = TRUE)
obj <- qread(glue("/data1/deyk/harry/RA_Xenium/data/post_qc_data_baysor/{sample_id}/final_version_seurat_obj.qs"))
obj <- BuildNicheAssay(obj, fov="fov", group.by="celltype_subcluster", neighbors.k=25, niches.k=5)
niche_assay <- obj[["niche"]]@counts
qsave(niche_assay, glue("/data1/deyk/harry/RA_Xenium/results/nicheassay/{sample_id}_niche_assay.qs"))