library(Seurat)
library(glue)
library(qs)
library(nicheDE)
library(clusterProfiler)
library(org.Hs.eg.db)
library(parallel)
library(ggplot2)
library(stringr)
library(ggsci)
library(reshape2)
library(scales)
library(hues)
library(RColorBrewer)
library(latex2exp)
library(MASS)
library(irr)
library(patchwork)
library(ggdark)
library(CellChat)
library(spdep)
library(SpatialExperiment)
library(ComplexHeatmap)
library(Polychrome)
library(scico)
library(SEraster)
library(dplyr)
library(tidyr)

all_ra_samples <- list.dirs("/data1/deyk/harry/RA_Xenium/data/post_qc_data_baysor/", recursive=FALSE, full.names=TRUE)
all_sample_ids <- str_extract(all_ra_samples, "RA\\d+[A-Z]*")
all_niche_assays <- lapply(all_sample_ids, function(sample_id){
    tmp <- qread(glue("/data1/deyk/harry/RA_Xenium/results/nicheassay/{sample_id}_niche_assay.qs"))
    colnames(tmp) <- paste(sample_id, colnames(tmp), sep="_")
    return(tmp)
})
common_cell_types <- Reduce(intersect, lapply(all_niche_assays, rownames))
all_niche_assays <- do.call(cbind, lapply(all_niche_assays, function(niche_assay){
    return(niche_assay[common_cell_types,])
}))
all_niche_assays <- CreateAssayObject(counts = all_niche_assays)
all_niche_assays <- ScaleData(all_niche_assays)
input_kmeans <- t(all_niche_assays@scale.data)
kmeans_res <- kmeans(
    x = input_kmeans,
    centers = 5,
    nstart = 30
  )
qsave(kmeans_res, glue("/data1/deyk/harry/RA_Xenium/results/nicheassay/kmeans_res/k_5_res.qs"))